#!/usr/bin/env bash
# Resolve o caminho real do executável (seguindo o symlink)
SCRIPT_FILEPATH="$(readlink -f "$0")"
SCRIPT_PATH="$(dirname -- "$SCRIPT_FILEPATH")"

cd $SCRIPT_PATH

GAME_REQ="Need put a Over The Wire game"

GAME=${1?$GAME_REQ}
shift

case $GAME in
	"bandit")
		cd bandit
		./bandit $@
		;;
	*)
		echo "invalid game" >&2
		exit 1
	;;
esac

exit 0
