#!/usr/bin/env bash

EXEC_FILEPATH=$(readlink -f $0)
EXEC_ROOTPATH=$(dirname -- $EXEC_FILEPATH)

cd $EXEC_ROOTPATH

source "./srcs/utils.sh"

[ -z "$1" ] && error 1 "available commands:" $(ls "./srcs/bin" | sed "s/\.sh$//g")

source "bandit.env" 2>/dev/null

CMD=${1}

shift

bash "./srcs/bin/${CMD}.sh" $@

